In [7]:
'''
 Q .Identify the shape and dimensions of an array
'''
import numpy as np
# Create array using array function
ages = np.array([[24, 12, 26],
                [8, 12, 46],
                [1, 2,  3]])
print('print different ages using array function:')
print(ages)
print("Dimensions of array is :", ages.ndim)
print("Shape of array is : ", ages.shape)


print different ages using array function:
[[24 12 26]
 [ 8 12 46]
 [ 1  2  3]]
Dimensions of array is : 2
Shape of array is :  (3, 3)
